name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Sync build
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: "-avzr --delete"
          path: "./docs/*"
          remote_path: "${{ secrets.SSH_DEPLOY_PATH }}"
          remote_host: "${{ secrets.SSH_REMOTE_HOST }}"
          remote_user: "${{ secrets.SSH_USER }}"
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
